version: '3.7'

services:

  nginx:
    volumes:
      - ./public:/srv/app/public:ro

  app:
    build:
      args:
        -  FPM_POOL_UID=${PHP_FPM_POOL_UID}
        -  FPM_POOL_GID=${PHP_FPM_POOL_GID}
    volumes:
      - ./:/srv/app:rw,cached
