version: '3.7'

services:

  app:
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  dbdata:
