version: '3.7'

services:

  nginx:
    build:
      context: .
      target: symfony_docker_nginx
    depends_on:
      - app
    ports:
      - '80:80'
    restart: unless-stopped

  app:
    build:
      context: .
      target: symfony_docker_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${SYMFONY_STABILITY:-stable}
    environment:
      - SYMFONY_VERSION
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
