version: '3.7'

services:

  nginx:
    volumes:
      - ./docker/elk/logs/nginx:/var/log/nginx:cached

  app:
    volumes:
      - ./docker/elk/logs/symfony:/srv/app/var/logs:cached

  elk:
    image: willdurand/elk
    ports:
      - "81:80"
    volumes:
      - ./docker/elk/logstash:/etc/logstash:cached
      - ./docker/elk/logstash/patterns:/opt/logstash/patterns:cached
      - ./docker/elk/logs/symfony:/var/log/symfony:cached
      - ./docker/elk/logs/nginx:/var/log/nginx:cached
